kind: Service
apiVersion: v1
metadata:
  name: mavenproject
spec:
  type: NodePort
  selector:
    app:mavenproject
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080 
      type: LoadBalancer
      
